### PR TITLE
Fix #43: Reposition Explore Button + Modify Styling

### LINKED ISSUE #43: Enhancement: Repositioning the Explore Button to a better place
Currently the explore button seems to be displaced which tends to distract the experience a bit. So this issue should 
1. Reposition the button
2. Can add further enhancements to the button to make it better

Screenshot 2024-10-26 at 7 21 23 PM

### PR DESCRIPTION
**Pull request by Malay-dev**
#### Description
This PR improves the user experience by repositioning the **Explore** button to enhance the visual flow and prevent any distractions. In addition to repositioning, the styling has been updated to align with the overall theme, making the button more consistent and appealing.

#### Changes
- Repositioned the **Explore** button for better alignment and visual hierarchy.
- Updated the button styling to match the theme, including adjustments in:
  - **Font style**
  - **Color scheme**
  - **Hover effects**

#### Screenshots (if applicable)
image

### CODE REVIEW

**Review by AalokeCode — CHANGES_REQUESTED** [review]
Can you move the button below cities heading and change it to explore places. Also are you using the button icon from phosphoricons?

**Comment by Malay-dev** [comment]
image

Check this

**Comment by AalokeCode** [comment]
Looks good. Small change and I'll merge it. Just remove the border, put the button below the cities subheading and make it the same font size as the cities list. Thats all!

**Comment by Malay-dev** [comment]
image
Here you go!

**Comment by AalokeCode** [comment]
Alright! Looks good for now. Thanks for your contribution :)

**Review by AalokeCode — APPROVED** [review]

**Pull request merged**
