### PR TITLE
Fix #5: Fix sidebar overflow

### LINKED ISSUE #5: Enhancement: Fix  Sidebar overflow issue
I noticed some blank space while looking at the app, and i believe it could be fixed by fixing the overflow issue of the sidebar. Please assign this to me with the hacktoberfest label

image

### PR DESCRIPTION
**Pull request by AbdurrahmanSogbesan**
Fixes #5 - Sidebar Overflow

What it looks like now:
image

### CODE REVIEW

**Comment by AalokeCode** [comment]
Hey! Thanks for the PR. We will update you in a bit

**Review by AalokeCode — APPROVED** [review]
Great! Now the sidebar looks better

**Review by HemanthTenneti — APPROVED** [review]
Good changes, can merge.

**Review by AalokeCode — CHANGES_REQUESTED** [review]
image
Hey there are quite a few problems regarding this PR

1. There are 2 Scrollbars on the rightmost side.
2. The page is a bit overflowed

If you can fix those, I'll merge the PR

**Comment by AbdurrahmanSogbesan** [comment]
> image Hey there are quite a few problems regarding this PR
> 1. There are 2 Scrollbars on the rightmost side.
> 2. The page is a bit overflowed
> 
> If you can fix those, I'll merge the PR

Alright, I'll fix the issue

**Review by AalokeCode — APPROVED** [review]
Hey! The code now seems to work perfectly. Thanks for your contribution :)

**Pull request merged**
