### PR TITLE
Enhancement: Cursor Pointer in search bar, Fix Javascript

### PR DESCRIPTION
**Pull request by Satya7390**
…is to visible in seconds and also added  some animations

Screenshot 2024-10-27 221547

### CODE REVIEW

**Review by AalokeCode — CHANGES_REQUESTED** [review]
Hey, the features are looking good! Just a couple of tweaks: Can you add a toggle for displaying time in seconds via a settings pop-up? This would let users easily switch formats as needed. Also, the animations could use a bit of fine-tuning they feel slightly distracting right now. Let’s aim for smoother, more subtle transitions that add to the cozy vibe we’re going for. Thanks!

**Comment by Satya7390** [comment]
> Hey, the features are looking good! Just a couple of tweaks: Can you add a toggle for displaying time in seconds via a settings pop-up? This would let users easily switch formats as needed. Also, the animations could use a bit of fine-tuning they feel slightly distracting right now. Let’s aim for smoother, more subtle transitions that add to the cozy vibe we’re going for. Thanks!

Yeah sure!!

**Comment by Satya7390** [comment]
curser pointer added in the input section

**Review by AalokeCode — APPROVED** [review]

**Comment by AalokeCode** [comment]
Good PR! Thanks for your contribution :)

**Pull request merged**
