### PR TITLE
Fix #1: Time updates in real-time

### LINKED ISSUE #1: Enhancement: Time updates in real-time
Time does not refresh automatically, please assign this issue to me.

### PR DESCRIPTION
**Pull request by AkshatGupta2005**
This commit will change time automatically.

Note - The time changed when the api changes its local time, I used setInterval for a function, It will change time after 1 min only if the time in api response changes.

### CODE REVIEW

**Comment by HemanthTenneti** [comment]
Hey @AkshatGupta2005, time does not update automatically. I think it must be a problem with the intervals you're calling the function in. I've tried checking it with 2-3 minute intervals of waiting and the time does not update.

Please look into it.
Regards.

**Review by AalokeCode — COMMENTED** [review]
Hey! I've checked the code. The API itself seems to be updating the time every 3-4 minutes. Can you figure out a method to update it every minute?

**Comment by AkshatGupta2005** [comment]
Yes, I did some research. We can use world time API to get local time, which can give time precious of every second, Give me some time, Let me try it.

**Comment by VBsaini** [comment]
can i give this a try?

**Comment by AkshatGupta2005** [comment]
Actually my code is almost complete.

**Comment by AalokeCode** [comment]
Hey @AkshatGupta2005! Are you still working on this?

**Comment by AkshatGupta2005** [comment]
Yeah, I am, Actually the api I am using to get time is not working properly. It has limited number of requests per hours. So it would be inefficient to add in this project.


Please suggest if you have any api which can provide time and does not have any request limit.

**Comment by AalokeCode** [comment]
Alright! I'll research and let you know

**Comment by AalokeCode** [comment]
Hey @AkshatGupta2005 I've found [this](https://timeapi.io/) website which provides the API for free at the moment

**Comment by AalokeCode** [comment]
@AkshatGupta2005 Please make sure to sync your PR. Cause there has been many changes

**Comment by AkshatGupta2005** [comment]
Hey guys have a look at it now. I guess I did everything perfectly, Time changes with accuracy of 1 second.

**Comment by AkshatGupta2005** [comment]
@HemanthTenneti @AalokeCode

**Comment by AalokeCode** [comment]
Alright! let me check

**Review by AalokeCode — APPROVED** [review]
Great PR! Thanks for your contribution :)

**Pull request merged**
