### PR TITLE
Fix #8: Temporary Responsive Design

### LINKED ISSUE #8: Enhancement: Adding mobile responsiveness
The application is not responsive, let me add boostrap and make it responsive, assign me this task
image

### PR DESCRIPTION
**Pull request by prishamehta01**
This pull request introduces enhancements to the index.html and style.css files to improve the overall user experience and responsiveness of the application.

Changes Made:
1. Adjusted layout for better usability on screens smaller than 768px.
2. Created an interactive effect on hover for the logo.

### CODE REVIEW

**Comment by prishamehta01** [comment]
Hey team,
Do check out and accept for hacktoberFest if you find it good.
Thank You.

**Review by AalokeCode — CHANGES_REQUESTED** [review]
Hey! The logo interaction seems fancy, But not sure about the mobile responsiveness. Can you make it a bit more better?

**Comment by prishamehta01** [comment]
Sure..will revert back by the end of the day!!

**Comment by prishamehta01** [comment]
@AalokeCode Have changed mobile responsive..this can be checked by inspect->click on toggle option on top left corner to check mobile responsiveness

**Review by AalokeCode — CHANGES_REQUESTED** [review]
Small Request. Can you make the sidebar like a toggle button?. If it isn't doable, no worries I'll merge the PR.

**Comment by prishamehta01** [comment]
I'll try to do it..if it's not possible, will let u know by EOD!

**Comment by AalokeCode** [comment]
Also, the logo interaction seems unnecessary. So can you also remove it?

**Comment by prishamehta01** [comment]
@AalokeCode Removed the logo styling, and toggle button doesn't seem possible, its hindering the normal view.
So, I would suggest it to be the same as previous one..
Can you please accept for hacktoberfest..if the other mobile responsiveness is enough?

**Comment by AalokeCode** [comment]
Alright! Lemme review the code and merge it

**Comment by AalokeCode** [comment]
@prishamehta01 Can you just fix the "Explore" Button. Other than that no issue. I'll merge it.

**Comment by AalokeCode** [comment]
Screenshot 2024-10-25 at 9 46 04 PM
The explore button seems to be broken in this PR.

**Comment by prishamehta01** [comment]
There is no explore button in the code?
This is what i see:
Website view for laptops and systems:
weather1
Mobile view:
weather2

**Comment by AalokeCode** [comment]
Okay! I figured out the mistake. I'll merge the PR. Thanks for your Contribution!

**Comment by prishamehta01** [comment]
@AalokeCode Okay!! Thank you so much. It was great working with you😄.

**Comment by AalokeCode** [comment]
@prishamehta01 The ending brackets weren't closed which was continued by the explore button code. So the button was broken. The explore button was introduced in the later commits. Anyways, I've fixed the issue. I greatly appreciate your efforts in updating the code accordingly. I'll still keep the mobile responsiveness issue open so that the people can improve your code.

**Review by AalokeCode — APPROVED** [review]

**Comment by prishamehta01** [comment]
@AalokeCode Sure, great to know that I could be of some help..I would appreciate if somebody else improve the responsiveness to much greater level.
Also, have you added hacktoberfest-accepted label? cuz, I wouldn't count on my profile otherwise😅

**Comment by AalokeCode** [comment]
@prishamehta01 Just check your profile once. If it doesn't show up, I'll add the hacktoberfest-accepted label

**Comment by prishamehta01** [comment]
Yup, it's showing..thanks a lot👍🏻 can I get ur linkedIn id to connect?

**Comment by AalokeCode** [comment]
Yeah! its there on my profile

**Pull request merged**
