### PR TITLE
Fix #26: Add a footer

### LINKED ISSUE #26: Chore: Add a footer
Hi,
Can I add this real quick for a Hacktoberfest entry?
image

Regards,
Cynthia.

### PR DESCRIPTION
**Pull request by CynthiaWahome**
This is for issue #26 
Added a footer with Rights Reserved and names of Developers

### CODE REVIEW

**Review by AalokeCode — CHANGES_REQUESTED** [review]
The Footer seems to be distracting a bit. Can you like do something to fix it?

**Comment by CynthiaWahome** [comment]
Sure thing @AalokeCode 
How does this look?

image

**Comment by AalokeCode** [comment]
It looks good! but can you try moving it to bottom of the sidebar instead and check?

**Comment by CynthiaWahome** [comment]
I think I messed this up @AalokeCode 
I dint make 16commits.
Should I open another PR instead?😔

**Comment by AalokeCode** [comment]
@CynthiaWahome I think its cause you synced the Fork. If you want to, just close and open another PR

**Comment by CynthiaWahome** [comment]
Thank you. I will do just that.

**Pull request closed without merging**
