### PR TITLE
Fix #31: Adding Typing Effect for Dynamic Place Name

### LINKED ISSUE #31: Enhancement: Improving Homepage with Title and Typing Effect
### Description
We would like to enhance the homepage by adding a title, a typing effect for dynamic text, and a description that captures the essence of our service. The typing effect should specifically display the name of a city to engage users effectively.

### Requirements
1. **Add a Title**: 
   - The title should be prominently displayed at the top of the homepage.

2. **Add a Typing Effect**:
   - Implement a typing effect for the city name, making it visually appealing and interactive.
   - The effect should simulate typing the city name on the screen, pausing briefly between letters.

3. **Add a Description**:
   - A brief description below the title that outlines what our service offers.

4. **Dynamic City Name Display**:
   - Create a placeholder for the city name that will be animated with the typing effect.

### Additional Notes
- Consider adding styling to enhance the visual appeal of the title and description.
- Review the typing effect speed to ensure it feels natural.

### PR DESCRIPTION
**Pull request by vivek-anand-singh**
## Description
This pull request addresses the typing effect portion of issue #31. It introduces an interactive typing animation for displaying the place name on the homepage. The typing effect aims to make the place name display visually appealing, with a natural typing speed and brief pauses to enhance user engagement.

## Changes Implemented
- **Typing Effect for Place Name**:  
  A typing animation has been added to dynamically display the Place name, simulating a typing motion for a more engaging user experience.

## Additional Notes
- The typing speed has been fine-tuned to feel natural, with slight pauses between each letter to improve readability.
- This change is a standalone enhancement to the homepage and can be built upon in future updates.

## Video Demonstration

https://github.com/user-attachments/assets/7b7162df-572b-4aab-94eb-8a6cf59cc031

### CODE REVIEW

**Review by AalokeCode — CHANGES_REQUESTED** [review]
Hey! It looks amazing but can you change the text position? cause in the middle it distracts the background

**Comment by vivek-anand-singh** [comment]
@AalokeCode Could you please recommend where to do this. I would be happy to do so

**Comment by vivek-anand-singh** [comment]
@AalokeCode Replaced the position to the bottom where place was originally written

https://github.com/user-attachments/assets/66835750-03a1-46b9-b694-b845efe95286

**Comment by AalokeCode** [comment]
Yeah! It looks good. But I suggest you remove that "Place: " text from there.

**Comment by vivek-anand-singh** [comment]
Hi @AalokeCode! As per your suggestion, I've removed the 'Place:' text. Let me know if there are any other issues. Thanks!

**Comment by AalokeCode** [comment]
Nothing else. Let me review the code and merge it!

**Review by AalokeCode — APPROVED** [review]
Great PR! Thanks for your contribution :)

**Comment by vivek-anand-singh** [comment]
Hi @AalokeCode! Thanks for merging the PR. If you have any other issues in this organization or elsewhere, I’d be happy to help out!

**Pull request merged**
