### PR TITLE
Fix #8: Add Mobile Responsiveness using plain CSS

### LINKED ISSUE #8: Enhancement: Adding mobile responsiveness
The application is not responsive, let me add boostrap and make it responsive, assign me this task
image

### PR DESCRIPTION
**Pull request by Anurag-singh-thakur**
i have made the application responsive using the plain css . attaching files so that you don't have to bother for the website look .
Now please merge it .
image
image

### CODE REVIEW

**Review by AalokeCode — CHANGES_REQUESTED** [review]
Hey! The website seems to be broken on my side.<br>
Screenshot 2024-10-25 at 4 40 50 PM

**Comment by Anurag-singh-thakur** [comment]
@AalokeCode what you want to say please make sure to explain for my better understandings..and the broken side i will fix it .

**Comment by AalokeCode** [comment]
So on my side, the 
desktop site and the mobile version seems to be broken. Can you recheck your code?
Screenshot 2024-10-25 at 7 42 02 PM

Screenshot 2024-10-25 at 7 42 53 PM

Screenshot 2024-10-25 at 7 43 12 PM

Screenshot 2024-10-25 at 7 43 23 PM

**Comment by ahmedrazabaloch** [comment]
@AalokeCode  can you assign it to me i will resolve this issue before the deadline of hacktoberfest because i wanna contribute in this month

**Pull request closed without merging**
